####### PI SERVER

freewriting:
    path: pages/
    tags: tags/
    patterns: patterns/

lists:
    path: json/

appery:
    db-id: 5fddc3bb2e22d76142f22f65
    coll-name: Tags

management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*" 
               
---

####### LOCAL LINUX

spring:
  config:
    activate:
      on-profile: local-linux

appery:
    coll-name: Tags_test

---

####### LOCAL MAC

spring:
  config:
    activate:
      on-profile: local-mac

appery:
    coll-name: Tags_test

