####### PI SERVER

lists:
    home: /home/pi/pi-lists/

---

####### LOCAL LINUX

spring:
    profiles: local-linux

lists:
    home: /mnt/disk2/home/egor/prog/cowon/

---

####### LOCAL MAC

spring:
    profiles: local-mac

lists:
    home: /Users/eabramovich/Documents/pi/json



