####### PI SERVER

home:
    path: /home/pi/

lists:
    path: Documents/pi-lists/

freewriting:
    path: Documents/pages/
    tags: Documents/tags/

---

####### LOCAL LINUX

spring:
    profiles: local-linux

home:
    path: /media/egor/3fac5c85-a0bd-4626-99ae-a3effcfe6043/home/egor/

lists:
    path: prog/cowon/

freewriting:
    path: Документы/Freewriting/pages/
    tags: Документы/Freewriting/tags/

---

####### LOCAL MAC

spring:
    profiles: local-mac

home:
    path: /Users/eabramovich/Documents/pi/

lists:
    path: json/

freewriting:
    path: fw/pages/
    tags: fw/tags/


