####### PI SERVER

home:
    path: /home/egor/

lists:
    path: Documents/pi-lists/

freewriting:
    path: Documents/fw/pages/
    tags: Documents/fw/tags/
    patterns: Documents/fw/patterns/

appery:
    db-id: 5fddc3bb2e22d76142f22f65
    coll-name: Tags

management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*" 
               
---

####### LOCAL LINUX

spring:
  config:
    activate:
      on-profile: local-linux

home:
    path: /home/egor/

lists:
    path: prog/cowon/

freewriting:
    path: pi/fw/pages/
    tags: pi/fw/tags/
    patterns: pi/fw/patterns/

appery:
    coll-name: Tags_test

---

####### LOCAL MAC

spring:
  config:
    activate:
      on-profile: local-mac
      
home:
    path: /Users/eabramovich/Documents/pi/

lists:
    path: json/

freewriting:
    path: fw/pages/
    tags: fw/tags/
    patterns: fw/patterns/

appery:
    coll-name: Tags_test

